// ─────────────────────────────────────────────────────────────────────────────
//  Hancock Motors — Inventaire véhicules
//
//  Pour AJOUTER un véhicule : copiez un objet existant, donnez-lui un id
//  unique (sans espaces, tirets uniquement), et remplissez tous les champs.
//
//  statut : 'Disponible' | 'Réservé' | 'Vendu'
//  photos : tableau d'URLs. La première est la vignette de la fiche listing.
//           Ajoutez autant d'URLs que vous voulez (20+), une par ligne.
// ─────────────────────────────────────────────────────────────────────────────

const CARS = [

  {
    id: 'hyundai-ix20-crdi-pack-business',
    statut: 'Disponible',
    marque: 'Hyundai',
    modele: 'ix20 1.6 CRDi 115 Pack Business',
    titre: 'Hyundai ix20 1.6 CRDi 115 ch Pack Business — toit ouvrant, clim auto',
    prix: '7 790 €',
    annee: 2012,
    km: 112000,
    carburant: 'Diesel',
    boite: 'Manuelle',
    puissance: '115 ch',
    cylindree: '1.6L CRDi',
    couleur_ext: 'Phantom Black métallisé',
    couleur_int: 'Tissu noir',
    portes: 5,
    places: 5,
    description: "Hyundai ix20 1.6 CRDi 115 ch finition Pack Business, boîte manuelle 6 rapports, traction. Mise en circulation 29/06/2012, 112 000 km. Équipé du toit ouvrant, de la peinture métallisée Phantom Black, de la climatisation automatique, du régulateur de vitesse, du volant cuir multifonctions et du pré-câblage caméra de recul. Garantie 12 mois. Entretien récent : 4 pneus neufs, amortisseurs avant neufs, vidange moteur effectuée. Reprise ou rachat de votre véhicule possible. Livraison possible partout en France métropolitaine, ou remise à la gare de Niort. Véhicule visible uniquement sur rendez-vous.",
    specs_extra: {
      'Mise en circulation': '29/06/2012',
      'Puissance fiscale': '6 CV',
      'Transmission': 'Traction',
      'Boîte de vitesse': 'Manuelle 6 rapports',
      'Énergie': 'Diesel',
      'Nombre de places': '5',
      'Garantie': '12 mois',
    },
    equipements: [
      // OPTIONS
      'Toit ouvrant',
      'Peinture métallisée Phantom Black',
      'Pré-câblage caméra de recul',
      // ENTRETIEN RÉCENT
      '4 pneus neufs',
      'Amortisseurs avant neufs',
      'Vidange moteur effectuée',
      // INTÉRIEUR
      'Accoudoir central AV avec rangement',
      'Accoudoir central AR',
      'Banquette AR coulissante, inclinable et rabattable 1/3 - 2/3',
      'Boîte à gants éclairée et réfrigérée',
      'Climatisation automatique',
      'Commandes audio au volant',
      'Direction assistée réglable en hauteur et profondeur',
      'Ordinateur de bord avec écran multifonction couleur',
      'Pommeau de levier de vitesse en cuir',
      'Prises auxiliaire et USB',
      'Radio CD / MP3 6 HP avec Bluetooth',
      'Sellerie tissu noir',
      'Siège conducteur réglable en hauteur',
      'Volant cuir multifonctions',
      // EXTÉRIEUR
      'Becquet arrière',
      'Boucliers AV/AR couleur caisse',
      'Feux de jour',
      'Phares antibrouillard',
      'Phares halogènes',
      'Rétroviseurs extérieurs électriques et dégivrants',
      'Vitres électriques AV et AR',
      'Vitres surteintées à l\'arrière',
      // CONFORT
      'Aide au démarrage en côte',
      'Allumage automatique des feux',
      'Bluetooth avec kit mains-libres',
      'Capteur de pluie et de luminosité',
      'Filtre à pollen',
      'Limiteur de vitesse',
      'Régulateur de vitesse',
      'Stop & Start (Blue Drive)',
      'Verrouillage centralisé à distance',
      // SÉCURITÉ
      'ABS avec assistance au freinage d\'urgence (AFU)',
      'Airbags frontaux, latéraux AV et rideaux AV/AR (6 airbags)',
      'Alarme et alarme périmétrique',
      'Antidémarrage électronique',
      'Appuis-tête avant actifs',
      'Contrôle dynamique de trajectoire ESP',
      'Détecteur de sous-gonflage',
      'EBD (répartiteur électronique de freinage)',
      'Fixations ISOFIX aux places AR',
      'Système antipatinage',
    ],
    photos: [
      // EXTÉRIEUR
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-1.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-2.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-3.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-4.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-5.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-6.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-7.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-8.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-9.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-10.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-11.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-12.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-13.jpg',
      // INTÉRIEUR
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-1.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-2.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-3.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-4.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-5.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-6.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-7.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-8.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-9.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-10.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-11.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-12.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-13.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-14.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-15.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-16.jpg',
      'Photos%20voiture/Hyundai%20ix20%201.6%20CRDi/hyundai-ix20-crdi-noir-interieur-17.jpg',
    ],
  },

  {
    id: 'mercedes-vito-119-cdi',
    statut: 'Disponible',
    marque: 'Mercedes-Benz',
    modele: 'Vito 119 CDI Mixto Extra-Long',
    titre: 'Mercedes-Benz Vito 119 CDI 190 ch 7G-Tronic — Mixto Extra-Long, 5 places',
    prix: '24 990 €',
    annee: 2017,
    km: 211000,
    carburant: 'Diesel',
    boite: 'Automatique',
    puissance: '190 ch',
    cylindree: '',
    couleur_ext: 'Gris Graphite métallisé (7368)',
    couleur_int: 'Tissu Caluma noir (VY2)',
    portes: 5,
    places: 5,
    description: "Mercedes-Benz Vito 119 CDI Mixto Extra-Long, moteur diesel de 190 ch, boîte automatique 7G-Tronic Plus, propulsion. Configuration Mixto Extra-Long 5 places, mise en circulation 10/2017, 211 000 km. Équipé du Pack Confort Mixto, des phares LED Intelligent Light System, d'un attelage Westfalia rétractable à rotule, d'une caméra de recul, du détecteur d'angle mort, de la climatisation automatique bi-zone THERMOTRONIC et des vitres arrière surteintées (Privacy Glass). Financement possible. Reprise ou rachat de votre véhicule possible. Livraison à domicile possible en France métropolitaine, ou remise à la gare de Niort. Véhicule visible uniquement sur rendez-vous.",
    specs_extra: {
      'Mise en circulation': '10/2017',
      'Carrosserie': 'Mixto Extra-Long 5 portes',
      'Boîte de vitesse': 'Automatique 7G-Tronic Plus',
      'Transmission': 'Propulsion',
      'Énergie': 'Diesel',
      'Nombre de places': '5',
    },
    equipements: [
      // OPTIONS
      'Peinture métallisée Gris Graphite (7368)',
      'Pack CONFORT Mixto',
      'Phares LED Intelligent Light System',
      'Attelage Westfalia rétractable avec rotule',
      'Vitres arrière surteintées (Privacy Glass)',
      'Caméra de recul',
      'Climatisation automatique bi-zone THERMOTRONIC',
      'Habillage intérieur version supérieure',
      // INTÉRIEUR
      'Volant cuir multifonction réglable en hauteur et profondeur',
      'Sièges avant tissu confort avec accoudoirs réglables (conducteur + passager)',
      'Banquette arrière 3 places avec accoudoir central rabattable',
      'Habillage complet du ciel de pavillon',
      'Revêtement de sol TPO dans le compartiment passagers',
      'Pare-soleil conducteur et passager avec miroirs de courtoisie éclairés',
      'Prises 12V arrière (gauche et droite)',
      'Touches multifonctions au volant',
      'Système Audio 20 CD avec écran couleur',
      'Pré-équipement navigation',
      'Préparation téléphone Bluetooth',
      'Pavé numérique central',
      // EXTÉRIEUR
      'Version Extra-Long',
      '2 portes coulissantes latérales (gauche et droite)',
      'Hayon arrière avec lunette dégivrante et essuie-glace',
      'Déflecteurs d\'air sur vitres avant',
      'Rétroviseurs extérieurs électriques, dégivrants et rabattables',
      'Antenne requin sur le toit',
      'Jantes alliage 17 pouces 5 branches',
      // CONFORT
      'Désembuage arrière et pare-brise MAX',
      'Système Start & Stop ECO',
      'Régulateur et limiteur de vitesse (Tempomat / LIM)',
      'Capteur de pluie (essuie-glaces automatiques)',
      'Allumage automatique des phares',
      'Vitres avant électriques',
      'Verrouillage centralisé avec télécommande',
      'Ordinateur de bord',
      // SÉCURITÉ
      'Collision Prevention Assist (alerte de collision + freinage d\'urgence)',
      'Détecteur d\'angle mort (Blind Spot Assist)',
      'Caméra de recul avec lignes directrices',
      'Radars de stationnement avant et arrière (PARKTRONIC)',
      'Attention Assist (alerte de somnolence)',
      'ESP avec bouton de désactivation',
      'ABS, ASR, EBV, BAS',
      '6 airbags',
      'Ceintures 3 points à toutes les places',
    ],
    photos: [
      // EXTÉRIEUR
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-1.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-2.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-3.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-4.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-5.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-6.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-7.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-8.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-9.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-10.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-11.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-12.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-13.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-14.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-15.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-16.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-17.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-18.jpg',
      // INTÉRIEUR
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-1.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-2.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-3.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-4.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-5.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-6.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-7.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-8.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-9.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-10.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-11.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-12.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-13.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-14.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-15.jpg',
      'Photos%20voiture/Mercedes%20Vito%20119%20CDI/mercedes-vito-119-cdi-gris-graphite-interieur-16.jpg',
    ],
  },

  {
    id: 'porsche-928-s4',
    statut: 'Disponible',
    marque: 'Porsche',
    modele: '928 S4',
    titre: 'Porsche 928 S4 320 ch — V8 5.0 boîte auto, historique complet',
    prix: '29 750 €',
    annee: 1990,
    km: 123860,
    carburant: 'Essence',
    boite: 'Automatique',
    puissance: '320 ch',
    cylindree: '5.0L V8',
    couleur_ext: 'Blanc',
    couleur_int: 'Cuir complet beige',
    portes: 3,
    places: 4,
    description: "Porsche 928 S4 de 1990, V8 5.0 atmosphérique de 320 ch, boîte automatique 4 rapports, propulsion. Carte grise française, importée du Japon en 2019 (très bon état de conservation). Plus de 22 000 € de factures d'entretien depuis 2019 chez un spécialiste Porsche 928 : courroie de distribution, pompe à eau, vidanges moteur et boîte, disques et plaquettes Pagid, amortisseurs Bilstein B6 (avant et arrière), radiateur, durites, calorstat, climatisation refaite (R134a), admission et joints moteur, couvre-culasse, tableau de bord avec afficheur LCD km/h (conversion pro). 4 pneus remplacés en 2021, très peu roulé depuis. Véhicule sain, fiable, parfaitement utilisable, aucun frais à prévoir. Révision complète incluse avant livraison. 2 clés. Visible uniquement sur rendez-vous.",
    specs_extra: {
      'Mise en circulation': '10/1990',
      'Carrosserie': 'Coupé 3 portes',
      'Puissance fiscale': '32 CV',
      'Transmission': 'Propulsion',
      'Nombre de clés': '2',
      'Provenance': 'Import Japon 2019, carte grise française',
      'Tableau de bord': 'Conversion km/h pro (afficheur LCD remplacé)',
    },
    equipements: [
      // INTÉRIEUR
      'Sellerie cuir complet',
      'Sièges électriques à mémoire',
      'Climatisation (refaite R134a)',
      'Tableau de bord digital LCD remplacé',
      'Autoradio MP3 / USB',
      'Volant cuir',
      'Vitres électriques',
      'Ordinateur de bord',
      'Éclairage intérieur',
      // EXTÉRIEUR
      'Jantes Porsche d\'origine',
      'Toit ouvrant électrique',
      'Échappement inox',
      'Rétroviseurs électriques',
      'Éléments peints carrosserie',
      // ENTRETIEN & MÉCANIQUE (depuis 2019, spécialiste Porsche 928)
      'Plus de 22 000 € de factures d\'entretien depuis 2019',
      'Courroie de distribution neuve',
      'Pompe à eau neuve',
      'Vidange moteur récente',
      'Vidange boîte automatique récente',
      'Disques et plaquettes Pagid neufs',
      'Amortisseurs Bilstein B6 neufs (AV + AR)',
      'Radiateur, durites et calorstat refaits',
      'Climatisation refaite (compresseur, condenseur, R134a)',
      'Admission complète et joints moteur remplacés',
      'Joints couvre-culasse remplacés',
      'Suspension : silent blocs, bras arrière, rotules révisés',
      'Moteur lève-vitre droit remplacé',
      '4 pneus remplacés en 2021 (très peu roulé depuis)',
    ],
    photos: [
      // EXTÉRIEUR
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-1.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-2.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-3.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-4.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-5.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-6.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-7.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-8.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-9.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-10.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-11.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-12.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-13.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-14.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-15.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-16.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-17.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-18.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-19.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-20.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-21.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-22.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-23.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-24.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-25.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-26.jpg',
      // INTÉRIEUR
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-1.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-2.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-3.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-4.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-5.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-6.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-7.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-8.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-9.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-10.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-11.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-12.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-13.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-14.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-15.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-16.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-17.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-18.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-19.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-20.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-21.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-22.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-23.jpg',
      'Photos%20voiture/Porsche%20928%20S4/porsche-928-s4-blanc-interieur-24.jpg',
    ],
  },

  {
    id: 'ford-mustang-gt-fastback-1968',
    statut: 'Disponible',
    marque: 'Ford',
    modele: 'Mustang GT Fastback 1968',
    titre: 'Ford Mustang GT Fastback 1968 — V8 302ci J-Code',
    prix: '81 990 €',
    annee: 1968,
    km: 80800,
    carburant: 'Essence',
    boite: 'Automatique',
    puissance: '230 ch',
    cylindree: '4.7L V8 302ci',
    couleur_ext: 'Noir (teinte d\'origine Sunlit Gold #3073-A)',
    couleur_int: 'Sellerie noire',
    portes: 2,
    places: 4,
    description: "Ford Mustang GT Fastback 1968, V8 302ci 4-barrels (J-code) de 230 ch, boîte automatique C-4 Select Shift. Configuration GT Equipment Group d'origine — 1 des 12 087 exemplaires produits en 1968. Produite le 17/11/1967 à l'usine Ford de Metuchen (New Jersey), vendue le 04/03/1968. Importée des USA en 2024, carte grise française. Restauration récente complète : trains roulants intégralement révisés, sellerie intérieure refaite à neuf, soubassement traité antigravillon, peinture noire tendue d'application récente. Authentifiée par Deluxe Marti Report (Kevin Marti, 2023) et rapport d'expertise FFEA — LZN Expertise Automobile (31/10/2024). Certificate of Title — State of Montana, notice d'utilisation d'origine fournie. Contrôle technique réalisé pour la vente. Volant Deluxe d'origine fourni avec le véhicule. 50 200 miles (~80 800 km). 3 clés. Véhicule visible uniquement sur rendez-vous.",
    specs_extra: {
      'Mise en circulation': '01/01/1968',
      'Carrosserie': '2-Door Fastback',
      'Puissance fiscale': '27 CV',
      'Nombre de clés': '3',
      'Transmission': 'Propulsion',
      'Kilométrage': '50 200 miles (~80 800 km)',
      'Authenticité': 'Deluxe Marti Report (2023) + Expertise FFEA (2024)',
      'Production': '1 des 12 087 GT Equipment Group de 1968',
      'Usine': 'Ford Metuchen (New Jersey) — produite 17/11/1967',
    },
    equipements: [
      // EXTÉRIEUR
      'Calandre GT avec antibrouillards intégrés',
      'Emblèmes GT sur ailes',
      'Double sortie d\'échappement chromée',
      'Jantes Styled Steel GT d\'origine',
      'Pneus BFGoodrich Radial T/A',
      'Peinture noire tendue, application récente',
      // INTÉRIEUR
      'Sellerie noire',
      'Bucket seats avant',
      'Banquette arrière rabattable (option d\'usine)',
      'Volant sport 3 branches monté (volant Deluxe d\'origine fourni)',
      'Tachymètre et trip-mètre',
      'Autoradio Kraco K7/cassette avec égaliseur',
      'Ceintures Deluxe',
      // MÉCANIQUE
      'V8 302ci 4-barrels (J-code)',
      'Cache-culbuteurs Edelbrock chromés',
      'Filtre à air chromé',
      'Faisceau d\'allumage performance',
      'Direction assistée',
      'Freins à disques avant assistés',
      'Boîte automatique C-4 Select Shift',
      // SÉCURITÉ
      'Coupe-batterie',
      'Roue de secours avec pneu F70x14 flancs blancs d\'origine',
      '3 clés fournies',
      // RESTAURATION
      'Restauration récente complète',
      'Trains roulants intégralement révisés',
      'Sellerie intérieure refaite à neuf',
      'Soubassement traité antigravillon',
      'Contrôle technique réalisé pour la vente',
    ],
    photos: [
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-1.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-2.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-3.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-4.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-5.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-6.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-7.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-8.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-9.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-10.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-11.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-12.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-13.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-14.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-15.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-16.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-17.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-18.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-19.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-20.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-21.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-22.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-23.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-24.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-25.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-26.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-27.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-28.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-29.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-30.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-31.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-32.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-33.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-34.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-35.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-36.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-37.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-38.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-39.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-40.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-41.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-42.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-43.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-44.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-45.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-46.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-47.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-48.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-49.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-50.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-51.jpg',
      'Photos%20voiture/Ford%20Mustang%20GT%201968/ford-mustang-gt-fastback-1968-noir-52.jpg',
    ],
  },

  {
    id: 'toyota-corolla-collection-122h',
    statut: 'Disponible',
    marque: 'Toyota',
    modele: 'Corolla',
    titre: 'Toyota Corolla Collection 1.8 Hybrid 122ch',
    prix: '18 990 €',
    annee: 2019,
    km: 76000,
    carburant: 'Hybride',
    boite: 'Automatique (CVT)',
    puissance: '122 ch',
    cylindree: '1.8L Hybrid',
    couleur_ext: 'Blanc Nacré bi-ton toit noir (2KR)',
    couleur_int: 'Cuir noir',
    portes: 5,
    places: 5,
    description: "Corolla Collection 122h en blanc nacré bi-ton toit noir, suivi Toyota complet depuis l'origine. Sellerie cuir, GPS, caméra de recul, keyless, sièges chauffants. Hybride automatique — sobre et fiable au quotidien. 2 clés.",
    specs_extra: {
      'Mise en circulation': '23/05/2019',
      'Puissance fiscale': '5 CV',
      'Garantie': 'Toyota 12 mois',
      'Nombre de clés': '2',
      'Transmission': 'Avant',
    },
    equipements: [
      // OPTIONS
      'Peinture bi-ton toit noir',
      'Sellerie cuir',
      // INTÉRIEUR
      'Écran tactile 8" Toyota Touch 2 with Go (GPS + Apple CarPlay + Android Auto)',
      'Instrumentation tête haute (HUD)',
      'Régulateur / limiteur de vitesse adaptatif (RSA)',
      'Sièges chauffants avant',
      'Accoudoir central avant',
      'Rétroviseur intérieur anti-éblouissement automatique',
      'Rétroviseurs extérieurs électriques et chauffants',
      'Volant gainé cuir',
      'Commandes au volant (audio, téléphone, régulateur)',
      'Climatisation automatique bi-zone',
      'Démarrage sans clé (Smart Entry & Start)',
      'Chargeur à induction pour smartphone',
      'Prise USB / 12V',
      // EXTÉRIEUR
      'Jantes alliage 17"',
      'Feux avant Full LED',
      'Feux arrière LED',
      'Toit panoramique',
      'Caméra de recul',
      'Capteurs de stationnement avant et arrière',
      'Essuie-glaces automatiques (pluie)',
      'Allumage automatique des feux',
      // CONFORT
      'Hayon électrique mains libres',
      'Vitres électriques avant et arrière',
      'Verrouillage centralisé',
      'Rétroviseurs rabattables électriquement',
      // SÉCURITÉ
      'Toyota Safety Sense (pré-collision, maintien de voie, reconnaissance panneaux)',
      'Alerte angle mort (BSM)',
      'Contrôle dynamique de trajectoire (VSC)',
      'Aide au démarrage en côte (HAC)',
      "Système d'appel d'urgence eCall",
      '6 airbags',
    ],
    photos: [
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-1.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-2.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-3.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-4.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-5.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-6.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-7.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-8.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-9.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-10.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-11.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-1.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-2.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-3.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-4.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-5.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-6.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-7.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-8.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-9.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-10.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-11.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-12.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-13.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-14.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-15.jpg',
      'Photos%20voiture/toyota-corolla-collection-blanc-nacre-biton-interieur-16.jpg',
    ],
  },

  {
    id: 'mercedes-cla-edition1-220d',
    statut: 'Disponible',
    marque: 'Mercedes',
    modele: 'CLA Édition 1 2.0 220D AMG Line',
    titre: 'Mercedes CLA Édition 1 2.0 220D 190ch AMG Line',
    prix: '29 990 €',
    annee: 2019,
    km: 127000,
    carburant: 'Diesel',
    boite: 'Automatique 8G-DCT',
    puissance: '190 ch',
    cylindree: '2.0L 1 950cm³',
    couleur_ext: 'Noir Cosmos 191',
    couleur_int: 'Tissu/cuir sport noir',
    portes: 4,
    places: 5,
    description: `Mercedes CLA Édition 1 220d AMG Line en très bel état. Finition haut de gamme avec le pack Édition 1, le pack Premium Plus et de nombreuses options. Écran MBUX 10", Keyless-Go, CarPlay, éclairage d'ambiance, kit carrosserie AMG. Véhicule garanti 12 mois, extension jusqu'à 36 mois possible. Reprise ou rachat de votre véhicule possible. Livraison toute France Métropolitaine.`,
    specs_extra: {
      'Carrosserie': 'Berline',
      'Puissance fiscale': '10 CV',
      'Émissions CO₂': '114 g/km',
      'Mise en circulation': '23/08/2019',
      'Transmission': 'Avant',
      'Nombre de clés': '2',
      'Réservoir': '51L',
      'Consommation mixte': '4,3L/100km',
      'Dimensions (L×l×h)': '4 688 × 1 830 × 1 444 mm',
      'Capacité du coffre': '460L',
      'Garantie': '12 mois (extension jusqu\'à 36 mois)',
    },
    options_supplementaires: [
      'Pack premium plus : 3 450 €',
      'Édition 1 : 2 500 €',
      'Peinture métallisée : 950 €',
      'Pack confort Keyless-Go : 550 €',
      'Intégration Smartphone : 400 €',
      'CarPlay : 370 €',
      'Éclairage d\'ambiance : 350 €',
    ],
    equipements: [
      // Intérieur
      'Accoudoir central AV',
      'Banquette AR rabattable 40/20/40',
      'Climatisation automatique thermotronic',
      'Connexion Bluetooth pour téléphone portable',
      'Dynamic Select',
      'Écran média 10"',
      'Fonction de démarrage sans clé Keyless-Go',
      'Interface USB-C vide-poches + 2 USB-C console AR',
      'MBUX système multimédia',
      'Pack connectivité navigation par disque dur',
      'Pack rétroviseurs',
      'Pavé tactile touchpad',
      'Sièges AV sport',
      'Système de commande vocale Hey Mercedes',
      'Tapis de sol AMG',
      'Volant sport multifonction cuir nappa',
      // Extérieur
      'Baguettes chromées autour du vitrage latéral',
      'Étriers de frein avec logo Mercedes-Benz',
      'Feux de stop adaptatifs',
      'Habillages des bas de caisse AMG peints dans le ton carrosserie',
      'Kit carrosserie AMG',
      'Pack Advantage',
      'Projecteurs LED hautes performances',
      // Sécurité
      'ABS et ASR',
      'Aide au parking active avec Parktronic',
      'Airbag genoux conducteur',
      'Airbags frontaux, latéraux et rideaux',
      'Assistant de stabilisation vent latéral',
      'Assistant limitation de vitesse',
      'Attention Assist (détection de somnolence)',
      'Avertisseur de franchissement de ligne actif',
      'BAS (freinage d\'urgence assisté)',
      'Caméra de recul',
      'Capteur de pluie et de luminosité',
      'Contrôle de pression des pneumatiques',
      'Frein de stationnement électrique avec Start Assist',
      'Freinage d\'urgence assisté actif',
      'Kit anti-crevaison Tirefit',
      'Système d\'appel d\'urgence Mercedes-Benz',
      'Tempomat (régulateur + limiteur de vitesse)',
    ],
    photos: [
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-20.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-2.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-3.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-5.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-6.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-14.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-15.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-4.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-19.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-11.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-18.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-7.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-10.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-12.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-16.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-1.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-8.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-9.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-17.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-13.jpg',
      'Photos%20voiture/Mercedes-Benz%20CLA%20220d/mercedes-cla-220d-amg-line-noir-cosmos-21.jpg',
    ],
  },

  // ── VÉHICULES VENDUS ─────────────────────────────────────────────────────────

  {
    id: 'porsche-boxster-981-gts',
    statut: 'Vendu',
    marque: 'Porsche', modele: "Boxster GTS 981",
    titre: "Porsche Boxster GTS 981 330ch",
    prix: 'Vendu', annee: 2014, km: 0,
    carburant: 'Essence', boite: 'Automatique PDK',
    puissance: '330 ch', cylindree: '3.4L H6',
    couleur_ext: 'Bleu', couleur_int: '',
    portes: 2, places: 2, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/porsche-boxster-981-gts-1.jpg'],
  },

  {
    id: 'porsche-boxster-s-981',
    statut: 'Vendu',
    marque: 'Porsche',
    modele: 'Boxster S 981',
    titre: 'Porsche Boxster S 981 315ch',
    prix: 'Vendu',
    annee: 2013,
    km: 62000,
    carburant: 'Essence',
    boite: 'Automatique PDK',
    puissance: '315 ch',
    cylindree: '3.4L H6',
    couleur_ext: 'Blanc',
    couleur_int: 'Cuir noir',
    portes: 2,
    places: 2,
    description: `Porsche Boxster S 981 en excellent état. Boîte PDK à double embrayage, Sport Chrono, jantes Carrera Sport 19". Entretien Porsche à jour, véhicule préparé et contrôlé par nos soins avant mise en vente.`,
    specs_extra: {
      'Carrosserie': 'Roadster',
      'Puissance fiscale': '19 CV',
      'Émissions CO₂': '210 g/km',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'Boîte PDK',
      'Sport Chrono',
      'Toit cabriolet électrique',
      'Pack Sport',
      'Jantes Carrera Sport 19"',
      'Bose Audio',
      'PASM (amortisseurs actifs)',
    ],
    photos: [
      'Photos%20voiture/vehicule%20vendue/porsche-boxster-s-981-1.jpg',
    ],
  },

  {
    id: 'bmw-m4-f83-cabriolet',
    statut: 'Vendu',
    marque: 'BMW',
    modele: 'M4 Cabriolet F83',
    titre: 'BMW M4 Cabriolet F83 3.0 431ch',
    prix: 'Vendu',
    annee: 2015,
    km: 89000,
    carburant: 'Essence',
    boite: 'Automatique',
    puissance: '431 ch',
    cylindree: '3.0L 6 cyl.',
    couleur_ext: 'Gris',
    couleur_int: 'Cuir noir',
    portes: 2,
    places: 4,
    description: `BMW M4 Cabriolet F83 en parfait état. Son 6 cylindres en ligne de 431ch offre des performances exceptionnelles. Pack M complet, carnet d'entretien BMW à jour. Toit cabriolet électrique révisé.`,
    specs_extra: {
      'Carrosserie': 'Cabriolet',
      'Puissance fiscale': '27 CV',
      'Émissions CO₂': '194 g/km',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'Pack M',
      'Toit cabriolet électrique',
      'Sièges cuir M',
      'Jantes M 19"',
      'Système audio premium',
      'Navigation BMW',
      'Head-up display',
    ],
    photos: [
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-1.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-2.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-3.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-4.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-5.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-6.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-7.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-8.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-9.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-10.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-11.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-12.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-13.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-14.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-15.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-16.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-17.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-18.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-19.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-20.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-21.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-22.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-23.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-24.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-25.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-26.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-27.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-28.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-29.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-30.jpg',
    ],
  },

  {
    id: 'bmw-m2-bleu',
    statut: 'Vendu',
    marque: 'BMW', modele: 'M2',
    titre: 'BMW M2 370ch',
    prix: 'Vendu', annee: 2017, km: 52000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '370 ch', cylindree: '3.0L',
    couleur_ext: 'Bleu', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-m2-bleu-1.jpg'],
  },

  {
    id: 'audi-rs5-coupe-blanc',
    statut: 'Vendu',
    marque: 'Audi', modele: 'RS5 Coupé',
    titre: 'Audi RS5 Coupé 4.2 V8 450ch',
    prix: 'Vendu', annee: 2012, km: 89000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '450 ch', cylindree: '4.2L V8',
    couleur_ext: 'Blanc', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-rs5-coupe-blanc-1.jpg'],
  },

  {
    id: 'audi-s7-sportback',
    statut: 'Vendu',
    marque: 'Audi', modele: "S7 Sportback 4.0 V8",
    titre: "Audi S7 Sportback 4.0 V8 450ch",
    prix: 'Vendu', annee: 2014, km: 0,
    carburant: 'Essence', boite: 'Automatique S tronic',
    puissance: '450 ch', cylindree: '4.0L V8 TFSI',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-s7-sportback-4-0-v8-1.jpg'],
  },

  {
    id: 'audi-sq5-bleu',
    statut: 'Vendu',
    marque: 'Audi', modele: 'SQ5 Plus',
    titre: 'Audi SQ5 Plus 3.0 TDI 340ch Quattro',
    prix: 'Vendu', annee: 2014, km: 131000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '340 ch', cylindree: '3.0L TDI',
    couleur_ext: 'Bleu', couleur_int: 'Cuir noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-sq5-bleu-1.jpg'],
  },

  {
    id: 'audi-tts-roadster-blanc',
    statut: 'Vendu',
    marque: 'Audi', modele: 'TTS Roadster',
    titre: 'Audi TTS Roadster 2.0 TFSI 272ch',
    prix: 'Vendu', annee: 2012, km: 64000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '272 ch', cylindree: '2.0L TFSI',
    couleur_ext: 'Blanc', couleur_int: 'Cuir noir',
    portes: 2, places: 2, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-tts-roadster-blanc-1.jpg'],
  },

  {
    id: 'mercedes-amg-a45-argent',
    statut: 'Vendu',
    marque: 'Mercedes', modele: 'AMG A45',
    titre: 'Mercedes-AMG A45 2.0 381ch 4MATIC',
    prix: 'Vendu', annee: 2018, km: 58000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '381 ch', cylindree: '2.0L',
    couleur_ext: 'Argent', couleur_int: 'Cuir noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-amg-a45-argent-1.jpg'],
  },

  {
    id: 'bmw-x3-m40i-bleu',
    statut: 'Vendu',
    marque: 'BMW', modele: "X3 M40i",
    titre: "BMW X3 M40i 360ch xDrive",
    prix: 'Vendu', annee: 2019, km: 0,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '360 ch', cylindree: '3.0L 6 cyl.',
    couleur_ext: 'Bleu', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-x3-m40i-bleu-1.jpg'],
  },

  {
    id: 'ford-mustang-gt-gris',
    statut: 'Vendu',
    marque: 'Ford', modele: 'Mustang GT',
    titre: 'Ford Mustang GT 5.0 V8 450ch',
    prix: 'Vendu', annee: 2019, km: 34000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '450 ch', cylindree: '5.0L V8',
    couleur_ext: 'Gris', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: [
      'Photos%20voiture/vehicule%20vendue/ford-mustang-gt-gris-1.jpg',
      'Photos%20voiture/vehicule%20vendue/ford-mustang-gt-gris-2.jpg',
    ],
  },

  {
    id: 'volkswagen-golf-r-akrapovic',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf R Akrapovic',
    titre: 'Volkswagen Golf R 2.0 TSI 310ch Akrapovic',
    prix: 'Vendu', annee: 2018, km: 47000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '310 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Blanc', couleur_int: 'Cuir sport noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-r-akrapovic-blanc-1.jpg'],
  },

  {
    id: 'volkswagen-golf-r-rouge',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf R',
    titre: 'Volkswagen Golf R 2.0 TSI 310ch 4Motion',
    prix: 'Vendu', annee: 2017, km: 54000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '310 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Rouge', couleur_int: 'Cuir sport noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-r-rouge-1.jpg'],
  },

  {
    id: 'mercedes-a250-petronas',
    statut: 'Vendu',
    marque: 'Mercedes', modele: 'A250 Édition 1 Petronas',
    titre: 'Mercedes A250 Édition 1 Petronas 211ch',
    prix: 'Vendu', annee: 2016, km: 61000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '211 ch', cylindree: '2.0L',
    couleur_ext: 'Gris', couleur_int: 'Cuir sport noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-a250-petronas-gris-1.jpg'],
  },

  {
    id: 'audi-s3-gris',
    statut: 'Vendu',
    marque: 'Audi', modele: 'S3 Sportback',
    titre: 'Audi S3 Sportback 2.0 TFSI 300ch',
    prix: 'Vendu', annee: 2014, km: 76000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '300 ch', cylindree: '2.0L TFSI',
    couleur_ext: 'Gris', couleur_int: 'Cuir noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-s3-gris-1.jpg'],
  },

  {
    id: 'volkswagen-scirocco-bleu',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Scirocco R',
    titre: 'Volkswagen Scirocco R 2.0 TSI 265ch',
    prix: 'Vendu', annee: 2013, km: 84000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '265 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Bleu', couleur_int: 'Cuir sport noir',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-scirocco-bleu-1.jpg'],
  },

  {
    id: 'vw-scirocco-noir',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Scirocco",
    titre: "Volkswagen Scirocco TSI",
    prix: 'Vendu', annee: 2010, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '', cylindree: '1.4L TSI',
    couleur_ext: 'Noir', couleur_int: '',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-scirocco-noir-1.jpg'],
  },

  {
    id: 'seat-leon-cupra-blanc',
    statut: 'Vendu',
    marque: 'SEAT', modele: 'Leon Cupra',
    titre: 'SEAT Leon Cupra 2.0 TSI 300ch',
    prix: 'Vendu', annee: 2017, km: 58000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '300 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Blanc', couleur_int: 'Tissu sport',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/seat-leon-cupra-blanc-1.jpg'],
  },

  {
    id: 'volkswagen-golf-gti-rouge-mk75',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf GTI Performance',
    titre: 'Volkswagen Golf GTI Performance 2.0 TSI 245ch',
    prix: 'Vendu', annee: 2018, km: 51000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '245 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Rouge', couleur_int: 'Tissu sport',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-gti-rouge-2.jpg'],
  },

  {
    id: 'volkswagen-golf-gti-blanc',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf GTI',
    titre: 'Volkswagen Golf GTI 2.0 TSI 230ch',
    prix: 'Vendu', annee: 2017, km: 62000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '230 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Blanc', couleur_int: 'Tissu sport',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-gti-blanc-1.jpg'],
  },

  {
    id: 'volkswagen-golf-gti-rouge-mk6',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf GTI',
    titre: 'Volkswagen Golf GTI 2.0 TSI 210ch Mk6',
    prix: 'Vendu', annee: 2012, km: 98000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '210 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Rouge', couleur_int: 'Tissu sport',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-gti-rouge-1.jpg'],
  },

  {
    id: 'triumph-tr4',
    statut: 'Vendu',
    marque: 'Triumph', modele: "TR4",
    titre: "Triumph TR4 — Roadster classique",
    prix: 'Vendu', annee: 1964, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '105 ch', cylindree: '2.1L',
    couleur_ext: 'Crème', couleur_int: '',
    portes: 2, places: 2, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/triumph-tr4-1.jpg'],
  },

  {
    id: 'mini-cooper-blackfriars',
    statut: 'Vendu',
    marque: 'MINI', modele: "Cooper Blackfriars",
    titre: "MINI Cooper Blackfriars — Édition limitée",
    prix: 'Vendu', annee: 2014, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '122 ch', cylindree: '1.6L',
    couleur_ext: 'Noir', couleur_int: '',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-blackfriars-1.jpg'],
  },

  {
    id: 'mini-jcw-cabriolet-gris',
    statut: 'Vendu',
    marque: 'MINI', modele: 'John Cooper Works Cabriolet',
    titre: 'MINI JCW Cabriolet 1.6 211ch',
    prix: 'Vendu', annee: 2010, km: 88000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '211 ch', cylindree: '1.6L',
    couleur_ext: 'Gris', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-s-cabriolet-gris-1.jpg'],
  },

  {
    id: 'mini-jcw-2021',
    statut: 'Vendu',
    marque: 'MINI', modele: "John Cooper Works",
    titre: "MINI John Cooper Works 231ch",
    prix: 'Vendu', annee: 2021, km: 0,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '231 ch', cylindree: '2.0L',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-jcw-2021-1.jpg'],
  },

  {
    id: 'vw-beetle',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Beetle",
    titre: "Volkswagen Beetle",
    prix: 'Vendu', annee: 2014, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '', cylindree: '',
    couleur_ext: 'Blanc', couleur_int: '',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-beetle-1.jpg'],
  },

  {
    id: 'audi-a6-avant-3-0-tdi-s-line',
    statut: 'Vendu',
    marque: 'Audi', modele: "A6 Avant 3.0 TDI S-Line",
    titre: "Audi A6 Avant 3.0 TDI 272ch S-Line Quattro",
    prix: 'Vendu', annee: 2016, km: 0,
    carburant: 'Diesel', boite: 'Automatique S tronic',
    puissance: '272 ch', cylindree: '3.0L V6 TDI',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-a6-avant-3-0-tdi-s-line-1.jpg'],
  },

  {
    id: 'range-rover-evoque',
    statut: 'Vendu',
    marque: 'Land Rover', modele: "Range Rover Evoque 2.2 Dynamic",
    titre: "Range Rover Evoque 2.2 SD4 Dynamic 190ch",
    prix: 'Vendu', annee: 2014, km: 0,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '190 ch', cylindree: '2.2L SD4',
    couleur_ext: 'Noir', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/range-rover-evoque-2-2-dynamic-1.jpg'],
  },

  {
    id: 'bmw-x5-blanc',
    statut: 'Vendu',
    marque: 'BMW', modele: 'X5',
    titre: 'BMW X5 xDrive40e',
    prix: 'Vendu', annee: 2017, km: 98000,
    carburant: 'Hybride', boite: 'Automatique',
    puissance: '313 ch', cylindree: '2.0L',
    couleur_ext: 'Blanc', couleur_int: 'Cuir noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-x5-blanc-1.jpg'],
  },

  {
    id: 'bmw-x5-gris',
    statut: 'Vendu',
    marque: 'BMW', modele: 'X5',
    titre: 'BMW X5 xDrive30d',
    prix: 'Vendu', annee: 2016, km: 112000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '258 ch', cylindree: '3.0L',
    couleur_ext: 'Gris', couleur_int: 'Cuir beige',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-x5-gris-1.jpg'],
  },

  {
    id: 'bmw-x3-m-sport-bleu',
    statut: 'Vendu',
    marque: 'BMW', modele: "X3 M-Sport",
    titre: "BMW X3 xDrive M-Sport",
    prix: 'Vendu', annee: 2014, km: 0,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '', cylindree: '',
    couleur_ext: 'Bleu', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-x3-m-sport-bleu-1.jpg'],
  },

  {
    id: 'volvo-xc60-t6-inscription',
    statut: 'Vendu',
    marque: 'Volvo', modele: "XC60 T6 Inscription",
    titre: "Volvo XC60 T6 Inscription AWD",
    prix: 'Vendu', annee: 2018, km: 0,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '320 ch', cylindree: '2.0L T6',
    couleur_ext: 'Bleu', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volvo-xc60-t6-inscription-1.jpg'],
  },

  {
    id: 'volvo-xc60-blanc',
    statut: 'Vendu',
    marque: 'Volvo', modele: "XC60 D5",
    titre: "Volvo XC60 D5 AWD",
    prix: 'Vendu', annee: 2012, km: 0,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '215 ch', cylindree: '2.4L D5',
    couleur_ext: 'Blanc', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volvo-xc60-blanc-1.jpg'],
  },

  {
    id: 'mercedes-gla-gris-mat',
    statut: 'Vendu',
    marque: 'Mercedes', modele: 'GLA AMG Line',
    titre: 'Mercedes GLA 200 AMG Line',
    prix: 'Vendu', annee: 2018, km: 72000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '156 ch', cylindree: '2.0L',
    couleur_ext: 'Gris mat', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-gla-gris-mat-1.jpg'],
  },

  {
    id: 'audi-q3-mk2-s-line-orange',
    statut: 'Vendu',
    marque: 'Audi', modele: "Q3 S-Line",
    titre: "Audi Q3 S-Line — Génération 2",
    prix: 'Vendu', annee: 2019, km: 0,
    carburant: 'Essence', boite: 'Automatique S tronic',
    puissance: '', cylindree: '',
    couleur_ext: 'Orange Pulse', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-q3-mk2-s-line-orange-1.jpg'],
  },

  {
    id: 'vw-tiguan-mk2-gris',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Tiguan",
    titre: "Volkswagen Tiguan — Génération 2",
    prix: 'Vendu', annee: 2018, km: 0,
    carburant: 'Diesel', boite: 'Automatique DSG',
    puissance: '', cylindree: '',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-tiguan-mk2-gris-1.jpg'],
  },

  {
    id: 'volkswagen-tiguan-noir',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Tiguan',
    titre: 'Volkswagen Tiguan 2.0 TDI 140ch 4Motion',
    prix: 'Vendu', annee: 2014, km: 118000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '140 ch', cylindree: '2.0L TDI',
    couleur_ext: 'Noir', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-tiguan-noir-1.jpg'],
  },

  {
    id: 'bmw-x1-noir',
    statut: 'Vendu',
    marque: 'BMW', modele: "X1 xLine",
    titre: "BMW X1 xLine F48",
    prix: 'Vendu', annee: 2020, km: 0,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '', cylindree: '',
    couleur_ext: 'Noir', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-x1-noir-1.jpg'],
  },

  {
    id: 'mercedes-a200-amg-rouge',
    statut: 'Vendu',
    marque: 'Mercedes', modele: 'A200 AMG Line',
    titre: 'Mercedes A200 AMG Line 163ch',
    prix: 'Vendu', annee: 2019, km: 43000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '163 ch', cylindree: '1.3L',
    couleur_ext: 'Rouge', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-a200-amg-rouge-1.jpg'],
  },

  {
    id: 'audi-a3-gris',
    statut: 'Vendu',
    marque: 'Audi', modele: 'A3 Sportback',
    titre: 'Audi A3 Sportback 2.0 TDI 150ch S Line',
    prix: 'Vendu', annee: 2017, km: 88000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '150 ch', cylindree: '2.0L TDI',
    couleur_ext: 'Gris', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-a3-gris-1.jpg'],
  },

  {
    id: 'bmw-serie-1-blanc',
    statut: 'Vendu',
    marque: 'BMW', modele: 'Série 1',
    titre: 'BMW 118i Série 1 F40',
    prix: 'Vendu', annee: 2020, km: 38000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '140 ch', cylindree: '1.5L',
    couleur_ext: 'Blanc', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-serie-1-blanc-1.jpg'],
  },

  {
    id: 'audi-a1-s-line-vert',
    statut: 'Vendu',
    marque: 'Audi', modele: "A1 Sportback S-Line",
    titre: "Audi A1 Sportback S-Line — Génération 2",
    prix: 'Vendu', annee: 2020, km: 0,
    carburant: 'Essence', boite: 'Automatique S tronic',
    puissance: '', cylindree: '',
    couleur_ext: 'Vert Tioman', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-a1-s-line-vert-1.jpg'],
  },

  {
    id: 'ford-kuga-st-line',
    statut: 'Vendu',
    marque: 'Ford', modele: "Kuga 2.0 TDCI 180 ST-Line",
    titre: "Ford Kuga 2.0 TDCI 180ch ST-Line AWD",
    prix: 'Vendu', annee: 2017, km: 0,
    carburant: 'Diesel', boite: 'Automatique Powershift',
    puissance: '180 ch', cylindree: '2.0L TDCI',
    couleur_ext: 'Blanc', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/ford-kuga-2-0-tdci-180-st-line-1.jpg'],
  },

  {
    id: 'volvo-v60-gris',
    statut: 'Vendu',
    marque: 'Volvo', modele: 'V60',
    titre: 'Volvo V60 D4 190ch Business',
    prix: 'Vendu', annee: 2018, km: 96000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '190 ch', cylindree: '2.0L D4',
    couleur_ext: 'Gris', couleur_int: 'Tissu gris',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volvo-v60-gris-1.jpg'],
  },

  {
    id: 'volvo-v40-d2',
    statut: 'Vendu',
    marque: 'Volvo', modele: "V40 D2",
    titre: "Volvo V40 D2",
    prix: 'Vendu', annee: 2015, km: 0,
    carburant: 'Diesel', boite: 'Manuelle',
    puissance: '120 ch', cylindree: '2.0L D2',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volvo-v40-d2-1.jpg'],
  },

  {
    id: 'vw-golf-8-tdi',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Golf 8 TDI",
    titre: "Volkswagen Golf 8 2.0 TDI",
    prix: 'Vendu', annee: 2021, km: 0,
    carburant: 'Diesel', boite: 'Automatique DSG',
    puissance: '', cylindree: '2.0L TDI',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-golf-8-tdi-1.jpg'],
  },

  {
    id: 'vw-golf-7-blanc',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Golf 7 Join",
    titre: "Volkswagen Golf 7 Join",
    prix: 'Vendu', annee: 2018, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '', cylindree: '',
    couleur_ext: 'Blanc', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-golf-7-blanc-1.jpg'],
  },

  {
    id: 'mini-cooper-rouge',
    statut: 'Vendu',
    marque: 'MINI', modele: "Cooper F56",
    titre: "MINI Cooper F56",
    prix: 'Vendu', annee: 2017, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '', cylindree: '',
    couleur_ext: 'Rouge', couleur_int: '',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-rouge-1.jpg'],
  },

  {
    id: 'mini-cooper-s-vert',
    statut: 'Vendu',
    marque: 'MINI', modele: 'Cooper S',
    titre: 'MINI Cooper S 2.0 192ch BVA',
    prix: 'Vendu', annee: 2019, km: 29000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '192 ch', cylindree: '2.0L',
    couleur_ext: 'Vert British Racing', couleur_int: 'Cuir noir',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-s-vert-1.jpg'],
  },

  {
    id: 'mini-cooper-bleu-r56',
    statut: 'Vendu',
    marque: 'MINI', modele: 'Cooper',
    titre: 'MINI Cooper 1.6 120ch',
    prix: 'Vendu', annee: 2012, km: 72000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '120 ch', cylindree: '1.6L',
    couleur_ext: 'Bleu', couleur_int: 'Tissu noir',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-bleu-1.jpg'],
  },

  {
    id: 'mini-cooper-s-r56-noir',
    statut: 'Vendu',
    marque: 'MINI', modele: "Cooper S R56",
    titre: "MINI Cooper S R56",
    prix: 'Vendu', annee: 2010, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '184 ch', cylindree: '1.6L Turbo',
    couleur_ext: 'Noir', couleur_int: '',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-s-r56-noir-1.jpg'],
  },

  {
    id: 'mini-cooper-f56-bleu',
    statut: 'Vendu',
    marque: 'MINI', modele: 'Cooper F56',
    titre: 'MINI Cooper F56 1.5 136ch BVA',
    prix: 'Vendu', annee: 2016, km: 54000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '136 ch', cylindree: '1.5L',
    couleur_ext: 'Bleu', couleur_int: 'Tissu noir',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-f56-bleu-1.jpg'],
  },

  {
    id: 'mini-countryman-blanc',
    statut: 'Vendu',
    marque: 'MINI', modele: 'Countryman',
    titre: 'MINI Countryman Cooper D 112ch',
    prix: 'Vendu', annee: 2013, km: 108000,
    carburant: 'Diesel', boite: 'Manuelle',
    puissance: '112 ch', cylindree: '1.6L D',
    couleur_ext: 'Blanc', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-countryman-blanc-1.jpg'],
  },

  {
    id: 'peugeot-308-gt-line',
    statut: 'Vendu',
    marque: 'Peugeot', modele: "308 GT Line",
    titre: "Peugeot 308 GT Line",
    prix: 'Vendu', annee: 2017, km: 0,
    carburant: 'Diesel', boite: 'Automatique EAT6',
    puissance: '', cylindree: '',
    couleur_ext: 'Blanc', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/peugeot-308-gt-line-blanc-1.jpg'],
  },

  {
    id: 'vw-polo-1-4-tsi-2014',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Polo 1.4 TSI",
    titre: "Volkswagen Polo 1.4 TSI",
    prix: 'Vendu', annee: 2014, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '', cylindree: '1.4L TSI',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-polo-1-4-tsi-2014-1.jpg'],
  },

  {
    id: 'vw-polo-1-6-tdi',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Polo 1.6 TDI",
    titre: "Volkswagen Polo 1.6 TDI",
    prix: 'Vendu', annee: 2016, km: 0,
    carburant: 'Diesel', boite: 'Manuelle',
    puissance: '', cylindree: '1.6L TDI',
    couleur_ext: 'Blanc', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-polo-1-6-tdi-1.jpg'],
  },

  {
    id: 'vw-polo-orange',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Polo",
    titre: "Volkswagen Polo",
    prix: 'Vendu', annee: 2018, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '', cylindree: '',
    couleur_ext: 'Orange Énergétique', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-polo-orange-1.jpg'],
  },

  {
    id: 'volkswagen-polo-trendline',
    statut: 'Vendu',
    marque: 'Volkswagen',
    modele: 'Polo 1.4i',
    titre: 'Volkswagen Polo 1.4i 85ch Trendline',
    prix: 'Vendu',
    annee: 2014,
    km: 102000,
    carburant: 'Essence',
    boite: 'Manuelle',
    puissance: '85 ch',
    cylindree: '1.4L',
    couleur_ext: 'Noir',
    couleur_int: 'Tissu noir',
    portes: 5,
    places: 5,
    description: `Volkswagen Polo en très bon état général. Première main, entretien suivi avec carnet disponible. CarPlay, Android Auto, régulateur de vitesse. Contrôle technique récent.`,
    specs_extra: {
      'Carrosserie': 'Citadine',
      'Puissance fiscale': '6 CV',
      'Émissions CO₂': '119 g/km',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'CarPlay / Android Auto',
      'Régulateur de vitesse',
      'Climatisation',
      'Vitres électriques',
      'Verrouillage centralisé',
    ],
    photos: [
      'https://hancockmotors.fr/wp-content/uploads/2024/12/Volkswagen-Polo-1.4-TSI-2014-2-640x640.jpg',
      // 'https://...',
    ],
  },

  {
    id: 'vw-t-roc-r-line',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "T-Roc R-Line 150 TDI",
    titre: "Volkswagen T-Roc R-Line 2.0 TDI 150ch",
    prix: 'Vendu', annee: 2019, km: 0,
    carburant: 'Diesel', boite: 'Automatique DSG',
    puissance: '150 ch', cylindree: '2.0L TDI',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-t-roc-r-line-1.jpg'],
  },

  {
    id: 'renault-captur',
    statut: 'Vendu',
    marque: 'Renault', modele: "Captur 1.3 TCe",
    titre: "Renault Captur 1.3 TCe",
    prix: 'Vendu', annee: 2020, km: 0,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '', cylindree: '1.3L TCe',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/renault-captur-1-3-1.jpg'],
  },

  {
    id: 'mercedes-v250d',
    statut: 'Vendu',
    marque: 'Mercedes', modele: "V250d",
    titre: "Mercedes-Benz V250d — Familial 7 places",
    prix: 'Vendu', annee: 2017, km: 0,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '190 ch', cylindree: '2.1L CDI',
    couleur_ext: 'Gris', couleur_int: '',
    portes: 5, places: 7, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-v250d-1.jpg'],
  },

  {
    id: 'peugeot-partner-tepee-beige',
    statut: 'Vendu',
    marque: 'Peugeot', modele: 'Partner Tepee',
    titre: 'Peugeot Partner Tepee 1.6 BlueHDI 100ch',
    prix: 'Vendu', annee: 2017, km: 78000,
    carburant: 'Diesel', boite: 'Manuelle',
    puissance: '100 ch', cylindree: '1.6L BlueHDI',
    couleur_ext: 'Beige', couleur_int: 'Tissu gris',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/peugeot-partner-tepee-beige-1.jpg'],
  },

  {
    id: 'peugeot-partner-tepee-marron',
    statut: 'Vendu',
    marque: 'Peugeot', modele: "Partner Tepee",
    titre: "Peugeot Partner Tepee 1.6 BlueHDI",
    prix: 'Vendu', annee: 2017, km: 0,
    carburant: 'Diesel', boite: 'Manuelle',
    puissance: '100 ch', cylindree: '1.6L BlueHDI',
    couleur_ext: 'Marron', couleur_int: '',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/peugeot-partner-tepee-marron-1.jpg'],
  },

  {
    id: 'vw-transporter-t5',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: "Transporter T5",
    titre: "Volkswagen Transporter T5 — Utilitaire",
    prix: 'Vendu', annee: 2014, km: 0,
    carburant: 'Diesel', boite: 'Manuelle',
    puissance: '', cylindree: '2.0L TDI',
    couleur_ext: 'Blanc', couleur_int: '',
    portes: 4, places: 3, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/vw-transporter-t5-blanc-1.jpg'],
  },

];

