// ─────────────────────────────────────────────────────────────────────────────
//  Hancock Motors — Inventaire véhicules
//
//  Pour AJOUTER un véhicule : copiez un objet existant, donnez-lui un id
//  unique (sans espaces, tirets uniquement), et remplissez tous les champs.
//
//  statut : 'Disponible' | 'Réservé' | 'Vendu'
//  photos : tableau d'URLs. La première est la vignette de la fiche listing.
//           Ajoutez autant d'URLs que vous voulez (20+), une par ligne.
// ─────────────────────────────────────────────────────────────────────────────

const CARS = [

  {
    id: 'porsche-928-s4',
    statut: 'Disponible',
    marque: 'Porsche',
    modele: '928 S4',
    titre: 'Porsche 928 S4 320ch V8 5.0',
    prix: '32 750 €',
    annee: 1990,
    km: 102000,
    carburant: 'Essence',
    boite: 'Automatique',
    puissance: '320 ch',
    cylindree: '5.0L V8',
    couleur_ext: 'Blanc',
    couleur_int: 'Cuir beige',
    portes: 2,
    places: 4,
    description: `Superbe Porsche 928 S4 en excellent état général. Cette icône des années 90 bénéficie d'un entretien suivi et d'un historique complet. Boîte automatique révisée, moteur V8 5.0L en parfait état. Carnet de bord disponible, contrôle technique récent. Un rare exemplaire à saisir.`,
    specs_extra: {
      'Carrosserie': 'Coupé',
      'Puissance fiscale': '20 CV',
      'Émissions CO₂': 'NC',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'Climatisation automatique',
      'Direction assistée',
      'Vitres électriques',
      'Verrouillage centralisé',
      'Régulateur de vitesse',
      'Jantes alliage',
      'Sièges cuir',
    ],
    photos: [
      'https://hancockmotors.fr/wp-content/uploads/2025/07/Porshce-928-S4-8-640x640.jpg',
      // Ajoutez vos photos supplémentaires ici, une par ligne :
      // 'https://...',
    ],
  },

  {
    id: 'bmw-m4-f83-cabriolet',
    statut: 'Disponible',
    marque: 'BMW',
    modele: 'M4 Cabriolet F83',
    titre: 'BMW M4 Cabriolet F83 3.0 431ch',
    prix: '42 990 €',
    annee: 2015,
    km: 89000,
    carburant: 'Essence',
    boite: 'Automatique',
    puissance: '431 ch',
    cylindree: '3.0L 6 cyl.',
    couleur_ext: 'Gris',
    couleur_int: 'Cuir noir',
    portes: 2,
    places: 4,
    description: `BMW M4 Cabriolet F83 en parfait état. Son 6 cylindres en ligne de 431ch offre des performances exceptionnelles. Pack M complet, carnet d'entretien BMW à jour. Toit cabriolet électrique révisé.`,
    specs_extra: {
      'Carrosserie': 'Cabriolet',
      'Puissance fiscale': '27 CV',
      'Émissions CO₂': '194 g/km',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'Pack M',
      'Toit cabriolet électrique',
      'Sièges cuir M',
      'Jantes M 19"',
      'Système audio premium',
      'Navigation BMW',
      'Head-up display',
    ],
    photos: [
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-1.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-2.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-3.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-4.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-5.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-6.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-7.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-8.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-9.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-10.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-11.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-12.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-13.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-14.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-15.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-16.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-17.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-18.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-19.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-20.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-21.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-22.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-23.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-24.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-25.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-26.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-27.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-28.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-29.jpg',
      'Photos voiture/BMW M4 Cab/bmw-m4-cabriolet-gris-mat-30.jpg',
    ],
  },

  {
    id: 'audi-q3-tdi-quattro',
    statut: 'Disponible',
    marque: 'Audi',
    modele: 'Q3 2.0 TDI Quattro',
    titre: 'Audi Q3 2.0 TDI 177ch Quattro',
    prix: '15 490 €',
    annee: 2014,
    km: 168000,
    carburant: 'Diesel',
    boite: 'Automatique',
    puissance: '177 ch',
    cylindree: '2.0L TDI',
    couleur_ext: 'Blanc',
    couleur_int: 'Tissu noir',
    portes: 5,
    places: 5,
    description: `Audi Q3 quattro en très bon état. Transmission intégrale idéale pour toutes conditions. Navigation MMI, sièges chauffants, attelage. Entretien Audi suivi, véhicule inspecté et préparé par nos soins.`,
    specs_extra: {
      'Carrosserie': 'SUV / Crossover',
      'Puissance fiscale': '13 CV',
      'Émissions CO₂': '145 g/km',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'Transmission Quattro',
      'Toit panoramique',
      'Navigation MMI',
      'Sièges chauffants',
      'Attelage',
      'Aide au stationnement',
      'Pack Navigation Plus',
    ],
    photos: [
      'https://hancockmotors.fr/wp-content/uploads/2024/12/Audi-Q3-177-Quattro-2.0-TDI-1-640x640.jpg',
      // 'https://...',
    ],
  },

  {
    id: 'porsche-boxster-s-981',
    statut: 'Disponible',
    marque: 'Porsche',
    modele: 'Boxster S 981',
    titre: 'Porsche Boxster S 981 315ch',
    prix: 'Sur demande',
    annee: 2013,
    km: 62000,
    carburant: 'Essence',
    boite: 'Automatique PDK',
    puissance: '315 ch',
    cylindree: '3.4L H6',
    couleur_ext: 'Blanc',
    couleur_int: 'Cuir noir',
    portes: 2,
    places: 2,
    description: `Porsche Boxster S 981 en excellent état. Boîte PDK à double embrayage, Sport Chrono, jantes Carrera Sport 19". Entretien Porsche à jour, véhicule préparé et contrôlé par nos soins avant mise en vente.`,
    specs_extra: {
      'Carrosserie': 'Roadster',
      'Puissance fiscale': '19 CV',
      'Émissions CO₂': '210 g/km',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'Boîte PDK',
      'Sport Chrono',
      'Toit cabriolet électrique',
      'Pack Sport',
      'Jantes Carrera Sport 19"',
      'Bose Audio',
      'PASM (amortisseurs actifs)',
    ],
    photos: [
      'https://hancockmotors.fr/wp-content/uploads/2025/06/Porsche-Boxster-S-981-2-scaled.jpg',
      // 'https://...',
    ],
  },

  {
    id: 'peugeot-208-bluehdi',
    statut: 'Disponible',
    marque: 'Peugeot',
    modele: '208 BlueHDI',
    titre: 'Peugeot 208 1.5 BlueHDI 100cv Active',
    prix: '14 990 €',
    annee: 2020,
    km: 51000,
    carburant: 'Diesel',
    boite: 'Manuelle',
    puissance: '100 ch',
    cylindree: '1.5L BlueHDI',
    couleur_ext: 'Gris',
    couleur_int: 'Tissu gris',
    portes: 5,
    places: 5,
    description: `Peugeot 208 en excellent état, faible kilométrage. Première main, carnet d'entretien complet. CarPlay, Android Auto, caméra de recul. Idéale pour usage quotidien, économique et fiable.`,
    specs_extra: {
      'Carrosserie': 'Citadine',
      'Puissance fiscale': '6 CV',
      'Émissions CO₂': '103 g/km',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'CarPlay / Android Auto',
      'Climatisation manuelle',
      'Régulateur de vitesse',
      'Caméra de recul',
      'Aide au stationnement arrière',
      'Radar de recul',
    ],
    photos: [
      'https://hancockmotors.fr/wp-content/uploads/2024/12/Peugeot-208-640x640.jpg',
      // 'https://...',
    ],
  },

  {
    id: 'mercedes-cla-edition1-220d',
    statut: 'Disponible',
    marque: 'Mercedes',
    modele: 'CLA Édition 1 2.0 220D AMG Line',
    titre: 'Mercedes CLA Édition 1 2.0 220D 190ch AMG Line',
    prix: '30 990 €',
    annee: 2019,
    km: 127000,
    carburant: 'Diesel',
    boite: 'Automatique 8G-DCT',
    puissance: '190 ch',
    cylindree: '2.0L 1 950cm³',
    couleur_ext: 'Noir Cosmos 191',
    couleur_int: 'Tissu/cuir sport noir',
    portes: 4,
    places: 5,
    description: `Mercedes CLA Édition 1 220d AMG Line en très bel état. Finition haut de gamme avec le pack Édition 1, le pack Premium Plus et de nombreuses options. Écran MBUX 10", Keyless-Go, CarPlay, éclairage d'ambiance, kit carrosserie AMG. Véhicule garanti 12 mois, extension jusqu'à 36 mois possible. Reprise ou rachat de votre véhicule possible. Livraison toute France Métropolitaine.`,
    specs_extra: {
      'Carrosserie': 'Berline',
      'Puissance fiscale': '10 CV',
      'Émissions CO₂': '114 g/km',
      'Mise en circulation': '23/08/2019',
      'Transmission': 'Avant',
      'Nombre de clés': '2',
      'Réservoir': '51L',
      'Consommation mixte': '4,3L/100km',
      'Dimensions (L×l×h)': '4 688 × 1 830 × 1 444 mm',
      'Capacité du coffre': '460L',
      'Garantie': '12 mois (extension jusqu\'à 36 mois)',
    },
    options_supplementaires: [
      'Pack premium plus : 3 450 €',
      'Édition 1 : 2 500 €',
      'Peinture métallisée : 950 €',
      'Pack confort Keyless-Go : 550 €',
      'Intégration Smartphone : 400 €',
      'CarPlay : 370 €',
      'Éclairage d\'ambiance : 350 €',
    ],
    equipements: [
      // Intérieur
      'Accoudoir central AV',
      'Banquette AR rabattable 40/20/40',
      'Climatisation automatique thermotronic',
      'Connexion Bluetooth pour téléphone portable',
      'Dynamic Select',
      'Écran média 10"',
      'Fonction de démarrage sans clé Keyless-Go',
      'Interface USB-C vide-poches + 2 USB-C console AR',
      'MBUX système multimédia',
      'Pack connectivité navigation par disque dur',
      'Pack rétroviseurs',
      'Pavé tactile touchpad',
      'Sièges AV sport',
      'Système de commande vocale Hey Mercedes',
      'Tapis de sol AMG',
      'Volant sport multifonction cuir nappa',
      // Extérieur
      'Baguettes chromées autour du vitrage latéral',
      'Étriers de frein avec logo Mercedes-Benz',
      'Feux de stop adaptatifs',
      'Habillages des bas de caisse AMG peints dans le ton carrosserie',
      'Kit carrosserie AMG',
      'Pack Advantage',
      'Projecteurs LED hautes performances',
      // Sécurité
      'ABS et ASR',
      'Aide au parking active avec Parktronic',
      'Airbag genoux conducteur',
      'Airbags frontaux, latéraux et rideaux',
      'Assistant de stabilisation vent latéral',
      'Assistant limitation de vitesse',
      'Attention Assist (détection de somnolence)',
      'Avertisseur de franchissement de ligne actif',
      'BAS (freinage d\'urgence assisté)',
      'Caméra de recul',
      'Capteur de pluie et de luminosité',
      'Contrôle de pression des pneumatiques',
      'Frein de stationnement électrique avec Start Assist',
      'Freinage d\'urgence assisté actif',
      'Kit anti-crevaison Tirefit',
      'Système d\'appel d\'urgence Mercedes-Benz',
      'Tempomat (régulateur + limiteur de vitesse)',
    ],
    photos: [
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-1.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-2.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-3.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-4.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-5.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-6.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-7.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-8.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-9.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-10.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-11.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-12.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-13.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-14.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-15.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-16.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-17.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-18.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-19.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-20.jpg',
      'photos voiture/Mercedes-Benz CLA 220d/mercedes-cla-220d-amg-line-noir-cosmos-21.jpg',
    ],
  },

  // ── VÉHICULES VENDUS ─────────────────────────────────────────────────────────

  {
    id: 'bmw-m4-f83-cabriolet',
    statut: 'Vendu',
    marque: 'BMW', modele: 'M4 F83 Cabriolet',
    titre: 'BMW M4 F83 Cabriolet 431ch',
    prix: 'Vendu', annee: 2015, km: 68000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '431 ch', cylindree: '3.0L',
    couleur_ext: 'Gris mat', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-m4-f82-coupe-gris-mat-1.jpg'],
  },

  {
    id: 'bmw-m2-bleu',
    statut: 'Vendu',
    marque: 'BMW', modele: 'M2',
    titre: 'BMW M2 370ch',
    prix: 'Vendu', annee: 2017, km: 52000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '370 ch', cylindree: '3.0L',
    couleur_ext: 'Bleu', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-m2-bleu-1.jpg'],
  },

  {
    id: 'bmw-x5-gris',
    statut: 'Vendu',
    marque: 'BMW', modele: 'X5',
    titre: 'BMW X5 xDrive30d',
    prix: 'Vendu', annee: 2016, km: 112000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '258 ch', cylindree: '3.0L',
    couleur_ext: 'Gris', couleur_int: 'Cuir beige',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-x5-gris-1.jpg'],
  },

  {
    id: 'bmw-x5-blanc',
    statut: 'Vendu',
    marque: 'BMW', modele: 'X5',
    titre: 'BMW X5 xDrive40e',
    prix: 'Vendu', annee: 2017, km: 98000,
    carburant: 'Hybride', boite: 'Automatique',
    puissance: '313 ch', cylindree: '2.0L',
    couleur_ext: 'Blanc', couleur_int: 'Cuir noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-x5-blanc-1.jpg'],
  },

  {
    id: 'bmw-serie-1-blanc',
    statut: 'Vendu',
    marque: 'BMW', modele: 'Série 1',
    titre: 'BMW 118i Série 1 F40',
    prix: 'Vendu', annee: 2020, km: 38000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '140 ch', cylindree: '1.5L',
    couleur_ext: 'Blanc', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/bmw-serie-1-blanc-1.jpg'],
  },

  {
    id: 'audi-rs5-coupe-blanc',
    statut: 'Vendu',
    marque: 'Audi', modele: 'RS5 Coupé',
    titre: 'Audi RS5 Coupé 4.2 V8 450ch',
    prix: 'Vendu', annee: 2012, km: 89000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '450 ch', cylindree: '4.2L V8',
    couleur_ext: 'Blanc', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-rs5-coupe-blanc-1.jpg'],
  },

  {
    id: 'audi-s3-gris',
    statut: 'Vendu',
    marque: 'Audi', modele: 'S3 Sportback',
    titre: 'Audi S3 Sportback 2.0 TFSI 300ch',
    prix: 'Vendu', annee: 2014, km: 76000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '300 ch', cylindree: '2.0L TFSI',
    couleur_ext: 'Gris', couleur_int: 'Cuir noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-s3-gris-1.jpg'],
  },

  {
    id: 'audi-sq5-bleu',
    statut: 'Vendu',
    marque: 'Audi', modele: 'SQ5 Plus',
    titre: 'Audi SQ5 Plus 3.0 TDI 340ch Quattro',
    prix: 'Vendu', annee: 2014, km: 131000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '340 ch', cylindree: '3.0L TDI',
    couleur_ext: 'Bleu', couleur_int: 'Cuir noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-sq5-bleu-1.jpg'],
  },

  {
    id: 'audi-a3-gris',
    statut: 'Vendu',
    marque: 'Audi', modele: 'A3 Sportback',
    titre: 'Audi A3 Sportback 2.0 TDI 150ch S Line',
    prix: 'Vendu', annee: 2017, km: 88000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '150 ch', cylindree: '2.0L TDI',
    couleur_ext: 'Gris', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-a3-gris-1.jpg'],
  },

  {
    id: 'audi-tts-roadster-blanc',
    statut: 'Vendu',
    marque: 'Audi', modele: 'TTS Roadster',
    titre: 'Audi TTS Roadster 2.0 TFSI 272ch',
    prix: 'Vendu', annee: 2012, km: 64000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '272 ch', cylindree: '2.0L TFSI',
    couleur_ext: 'Blanc', couleur_int: 'Cuir noir',
    portes: 2, places: 2, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/audi-tts-roadster-blanc-1.jpg'],
  },

  {
    id: 'mercedes-amg-a45-argent',
    statut: 'Vendu',
    marque: 'Mercedes', modele: 'AMG A45',
    titre: 'Mercedes-AMG A45 2.0 381ch 4MATIC',
    prix: 'Vendu', annee: 2018, km: 58000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '381 ch', cylindree: '2.0L',
    couleur_ext: 'Argent', couleur_int: 'Cuir noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-amg-a45-argent-1.jpg'],
  },

  {
    id: 'mercedes-gla-gris-mat',
    statut: 'Vendu',
    marque: 'Mercedes', modele: 'GLA AMG Line',
    titre: 'Mercedes GLA 200 AMG Line',
    prix: 'Vendu', annee: 2018, km: 72000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '156 ch', cylindree: '2.0L',
    couleur_ext: 'Gris mat', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-gla-gris-mat-1.jpg'],
  },

  {
    id: 'mercedes-a250-petronas',
    statut: 'Vendu',
    marque: 'Mercedes', modele: 'A250 Édition 1 Petronas',
    titre: 'Mercedes A250 Édition 1 Petronas 211ch',
    prix: 'Vendu', annee: 2016, km: 61000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '211 ch', cylindree: '2.0L',
    couleur_ext: 'Gris', couleur_int: 'Cuir sport noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-a250-petronas-gris-1.jpg'],
  },

  {
    id: 'mercedes-a200-amg-rouge',
    statut: 'Vendu',
    marque: 'Mercedes', modele: 'A200 AMG Line',
    titre: 'Mercedes A200 AMG Line 163ch',
    prix: 'Vendu', annee: 2019, km: 43000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '163 ch', cylindree: '1.3L',
    couleur_ext: 'Rouge', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mercedes-a200-amg-rouge-1.jpg'],
  },

  {
    id: 'volkswagen-golf-r-akrapovic',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf R Akrapovic',
    titre: 'Volkswagen Golf R 2.0 TSI 310ch Akrapovic',
    prix: 'Vendu', annee: 2018, km: 47000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '310 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Blanc', couleur_int: 'Cuir sport noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-r-akrapovic-blanc-1.jpg'],
  },

  {
    id: 'volkswagen-golf-r-rouge',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf R',
    titre: 'Volkswagen Golf R 2.0 TSI 310ch 4Motion',
    prix: 'Vendu', annee: 2017, km: 54000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '310 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Rouge', couleur_int: 'Cuir sport noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-r-rouge-1.jpg'],
  },

  {
    id: 'volkswagen-golf-gti-blanc',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf GTI',
    titre: 'Volkswagen Golf GTI 2.0 TSI 230ch',
    prix: 'Vendu', annee: 2017, km: 62000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '230 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Blanc', couleur_int: 'Tissu sport',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-gti-blanc-1.jpg'],
  },

  {
    id: 'volkswagen-golf-gti-rouge-mk75',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf GTI Performance',
    titre: 'Volkswagen Golf GTI Performance 2.0 TSI 245ch',
    prix: 'Vendu', annee: 2018, km: 51000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '245 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Rouge', couleur_int: 'Tissu sport',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-gti-rouge-2.jpg'],
  },

  {
    id: 'volkswagen-golf-gti-rouge-mk6',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Golf GTI',
    titre: 'Volkswagen Golf GTI 2.0 TSI 210ch Mk6',
    prix: 'Vendu', annee: 2012, km: 98000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '210 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Rouge', couleur_int: 'Tissu sport',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-golf-gti-rouge-1.jpg'],
  },

  {
    id: 'volkswagen-scirocco-bleu',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Scirocco R',
    titre: 'Volkswagen Scirocco R 2.0 TSI 265ch',
    prix: 'Vendu', annee: 2013, km: 84000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '265 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Bleu', couleur_int: 'Cuir sport noir',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-scirocco-bleu-1.jpg'],
  },

  {
    id: 'volkswagen-tiguan-noir',
    statut: 'Vendu',
    marque: 'Volkswagen', modele: 'Tiguan',
    titre: 'Volkswagen Tiguan 2.0 TDI 140ch 4Motion',
    prix: 'Vendu', annee: 2014, km: 118000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '140 ch', cylindree: '2.0L TDI',
    couleur_ext: 'Noir', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volkswagen-tiguan-noir-1.jpg'],
  },

  {
    id: 'seat-leon-cupra-blanc',
    statut: 'Vendu',
    marque: 'SEAT', modele: 'Leon Cupra',
    titre: 'SEAT Leon Cupra 2.0 TSI 300ch',
    prix: 'Vendu', annee: 2017, km: 58000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '300 ch', cylindree: '2.0L TSI',
    couleur_ext: 'Blanc', couleur_int: 'Tissu sport',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/seat-leon-cupra-blanc-1.jpg'],
  },

  {
    id: 'ford-mustang-gt-gris',
    statut: 'Vendu',
    marque: 'Ford', modele: 'Mustang GT',
    titre: 'Ford Mustang GT 5.0 V8 450ch',
    prix: 'Vendu', annee: 2019, km: 34000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '450 ch', cylindree: '5.0L V8',
    couleur_ext: 'Gris', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/ford-mustang-gt-gris-1.jpg'],
  },

  {
    id: 'volvo-v60-gris',
    statut: 'Vendu',
    marque: 'Volvo', modele: 'V60',
    titre: 'Volvo V60 D4 190ch Business',
    prix: 'Vendu', annee: 2018, km: 96000,
    carburant: 'Diesel', boite: 'Automatique',
    puissance: '190 ch', cylindree: '2.0L D4',
    couleur_ext: 'Gris', couleur_int: 'Tissu gris',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/volvo-v60-gris-1.jpg'],
  },

  {
    id: 'peugeot-partner-tepee-beige',
    statut: 'Vendu',
    marque: 'Peugeot', modele: 'Partner Tepee',
    titre: 'Peugeot Partner Tepee 1.6 BlueHDI 100ch',
    prix: 'Vendu', annee: 2017, km: 78000,
    carburant: 'Diesel', boite: 'Manuelle',
    puissance: '100 ch', cylindree: '1.6L BlueHDI',
    couleur_ext: 'Beige', couleur_int: 'Tissu gris',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/peugeot-partner-tepee-beige-1.jpg'],
  },

  {
    id: 'mini-cooper-s-vert',
    statut: 'Vendu',
    marque: 'MINI', modele: 'Cooper S',
    titre: 'MINI Cooper S 2.0 192ch BVA',
    prix: 'Vendu', annee: 2019, km: 29000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '192 ch', cylindree: '2.0L',
    couleur_ext: 'Vert British Racing', couleur_int: 'Cuir noir',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-s-vert-1.jpg'],
  },

  {
    id: 'mini-cooper-bleu-r56',
    statut: 'Vendu',
    marque: 'MINI', modele: 'Cooper',
    titre: 'MINI Cooper 1.6 120ch',
    prix: 'Vendu', annee: 2012, km: 72000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '120 ch', cylindree: '1.6L',
    couleur_ext: 'Bleu', couleur_int: 'Tissu noir',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-bleu-1.jpg'],
  },

  {
    id: 'mini-cooper-f56-bleu',
    statut: 'Vendu',
    marque: 'MINI', modele: 'Cooper F56',
    titre: 'MINI Cooper F56 1.5 136ch BVA',
    prix: 'Vendu', annee: 2016, km: 54000,
    carburant: 'Essence', boite: 'Automatique',
    puissance: '136 ch', cylindree: '1.5L',
    couleur_ext: 'Bleu', couleur_int: 'Tissu noir',
    portes: 3, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-f56-bleu-1.jpg'],
  },

  {
    id: 'mini-jcw-cabriolet-gris',
    statut: 'Vendu',
    marque: 'MINI', modele: 'John Cooper Works Cabriolet',
    titre: 'MINI JCW Cabriolet 1.6 211ch',
    prix: 'Vendu', annee: 2010, km: 88000,
    carburant: 'Essence', boite: 'Manuelle',
    puissance: '211 ch', cylindree: '1.6L',
    couleur_ext: 'Gris', couleur_int: 'Cuir noir',
    portes: 2, places: 4, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-cooper-s-cabriolet-gris-1.jpg'],
  },

  {
    id: 'mini-countryman-blanc',
    statut: 'Vendu',
    marque: 'MINI', modele: 'Countryman',
    titre: 'MINI Countryman Cooper D 112ch',
    prix: 'Vendu', annee: 2013, km: 108000,
    carburant: 'Diesel', boite: 'Manuelle',
    puissance: '112 ch', cylindree: '1.6L D',
    couleur_ext: 'Blanc', couleur_int: 'Tissu noir',
    portes: 5, places: 5, description: '', specs_extra: {}, equipements: [],
    photos: ['Photos%20voiture/vehicule%20vendue/mini-countryman-blanc-1.jpg'],
  },

  {
    id: 'volkswagen-polo-trendline',
    statut: 'Disponible',
    marque: 'Volkswagen',
    modele: 'Polo 1.4i',
    titre: 'Volkswagen Polo 1.4i 85ch Trendline',
    prix: '9 990 €',
    annee: 2014,
    km: 102000,
    carburant: 'Essence',
    boite: 'Manuelle',
    puissance: '85 ch',
    cylindree: '1.4L',
    couleur_ext: 'Noir',
    couleur_int: 'Tissu noir',
    portes: 5,
    places: 5,
    description: `Volkswagen Polo en très bon état général. Première main, entretien suivi avec carnet disponible. CarPlay, Android Auto, régulateur de vitesse. Contrôle technique récent.`,
    specs_extra: {
      'Carrosserie': 'Citadine',
      'Puissance fiscale': '6 CV',
      'Émissions CO₂': '119 g/km',
      'Garantie': 'Sur demande',
    },
    equipements: [
      'CarPlay / Android Auto',
      'Régulateur de vitesse',
      'Climatisation',
      'Vitres électriques',
      'Verrouillage centralisé',
    ],
    photos: [
      'https://hancockmotors.fr/wp-content/uploads/2024/12/Volkswagen-Polo-1.4-TSI-2014-2-640x640.jpg',
      // 'https://...',
    ],
  },

];

