name: Deploy to test.hancockmotors.fr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy via FTP to o2switch
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /test.hancockmotors.fr/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            site.zip
            photos-voiture.zip
